"""empty message

Revision ID: 43cd0ddb67cb
Revises: 8e51dbc2263a
Create Date: 2019-04-29 13:34:38.177816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cd0ddb67cb'
down_revision = '8e51dbc2263a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_time')
    # ### end Alembic commands ###
