"""empty message

Revision ID: 8e51dbc2263a
Revises: 
Create Date: 2019-04-15 10:28:45.718545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e51dbc2263a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('blodid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blogtopic', sa.String(length=100), nullable=False),
    sa.Column('blogcontent', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('blodid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blog')
    # ### end Alembic commands ###
